import { useEffect, useState, type FormEvent } from 'react'
import { AdminPagination, AdminTable } from './AdminTable'
import { deleteAdminTeam, getAdminTeams, saveAdminTeam, type AdminTeam } from '../services/admin'
export function AdminTeams() {
  const [items, setItems] = useState<AdminTeam[]>([]); const [page, setPage] = useState({ page: 1, total_pages: 1 }); const [editing, setEditing] = useState<AdminTeam | null>(null); const [isFormOpen, setIsFormOpen] = useState(false); const [form, setForm] = useState({ name: '', manager_id: '' }); const [error, setError] = useState('')
  function load(nextPage = 1) { getAdminTeams(nextPage).then((result) => { setItems(result.teams); setPage(result.pagination) }).catch((reason: Error) => setError(reason.message)) }
  useEffect(() => { load() }, [])
  function edit(team?: AdminTeam) { setEditing(team ?? null); setIsFormOpen(true); setForm(team ? { name: team.name, manager_id: team.manager_id?.toString() ?? '' } : { name: '', manager_id: '' }) }
  async function submit(event: FormEvent) { event.preventDefault(); try { await saveAdminTeam({ ...form, id: editing?.id, manager_id: Number(form.manager_id) }); setEditing(null); setIsFormOpen(false); load(page.page) } catch (reason) { setError(reason instanceof Error ? reason.message : 'Unable to save team.') } }
  async function remove(id: number) { if (!window.confirm('Delete this team?')) return; try { await deleteAdminTeam(id); load(page.page) } catch (reason) { setError(reason instanceof Error ? reason.message : 'Unable to delete team.') } }
  return <div><div className="panel-title"><div><p className="eyebrow">Structure</p><h2>Teams</h2></div><button className="primary-button" onClick={() => edit()}>+ New team</button></div>{error && <p className="error-message">{error}</p>}<AdminTable headers={['Name', 'Manager', 'Actions']}>{items.map((team) => <tr key={team.id}><td>{team.name}</td><td>{team.manager_email ?? 'No manager'}</td><td><button className="table-button" onClick={() => edit(team)}>Edit</button><button className="table-button danger-button" onClick={() => remove(team.id)}>Delete</button></td></tr>)}</AdminTable><AdminPagination page={page.page} totalPages={page.total_pages} onChange={load}/>{isFormOpen && <form className="admin-form" onSubmit={submit}><h3>{editing ? 'Edit team' : 'Create team'}</h3><div className="form-grid"><label className="field"><span>Name</span><input required value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })}/></label><label className="field"><span>Manager ID</span><input required inputMode="numeric" value={form.manager_id} onChange={(e) => setForm({ ...form, manager_id: e.target.value })}/></label></div><button className="submit-button" type="submit">Save team</button><button type="button" className="text-button cancel-button" onClick={() => { setEditing(null); setIsFormOpen(false) }}>Cancel</button></form>}</div>
}