import { useEffect, useState, type FormEvent } from 'react'
import { AdminPagination, AdminTable } from './AdminTable'
import { getAdminCategories, saveAdminCategory, type AdminCategory } from '../services/admin'
export function AdminCategories() {
  const [items, setItems] = useState<AdminCategory[]>([]); const [page, setPage] = useState({ page: 1, total_pages: 1 }); const [editing, setEditing] = useState<AdminCategory | null>(null); const [isFormOpen, setIsFormOpen] = useState(false); const [form, setForm] = useState({ name: '', auto_approve_limit: '', active: true }); const [error, setError] = useState('')
  function load(nextPage = 1) { getAdminCategories({ page: nextPage, per_page: 5 }).then((result) => { setItems(result.categories); setPage(result.pagination) }).catch((reason: Error) => setError(reason.message)) }
  useEffect(() => { load() }, [])
  function edit(category?: AdminCategory) { setEditing(category ?? null); setIsFormOpen(true); setForm(category ? { name: category.name, auto_approve_limit: category.auto_approve_limit, active: category.active } : { name: '', auto_approve_limit: '', active: true }) }
  async function submit(event: FormEvent) { event.preventDefault(); try { await saveAdminCategory({ ...form, id: editing?.id }); setEditing(null); setIsFormOpen(false); load(page.page) } catch (reason) { setError(reason instanceof Error ? reason.message : 'Unable to save category.') } }
  return <div><div className="panel-title"><div><p className="eyebrow">Policy</p><h2>Categories</h2></div><button className="primary-button" onClick={() => edit()}>+ New category</button></div>{error && <p className="error-message">{error}</p>}<AdminTable headers={['Name', 'Auto-approve limit', 'Status', 'Actions']}>{items.map((category) => <tr key={category.id}><td>{category.name}</td><td>${category.auto_approve_limit}</td><td><span className={category.active ? 'state' : 'state state-rejected'}>{category.active ? 'Active' : 'Inactive'}</span></td><td><button className="table-button" onClick={() => edit(category)}>Edit</button></td></tr>)}</AdminTable><AdminPagination page={page.page} totalPages={page.total_pages} onChange={load}/>{isFormOpen && <form className="admin-form" onSubmit={submit}><h3>{editing ? 'Edit category' : 'Create category'}</h3><div className="form-grid"><label className="field"><span>Name</span><input required value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })}/></label><label className="field"><span>Auto-approve limit</span><input type="number" min="0" step="0.01" required value={form.auto_approve_limit} onChange={(e) => setForm({ ...form, auto_approve_limit: e.target.value })}/></label></div><label className="check-field"><input type="checkbox" checked={form.active} onChange={(e) => setForm({ ...form, active: e.target.checked })}/> Active</label><button className="submit-button" type="submit">Save category</button><button type="button" className="text-button cancel-button" onClick={() => { setEditing(null); setIsFormOpen(false) }}>Cancel</button></form>}</div>
}