import { useEffect, useState } from 'react'
import { AdminPagination, AdminTable } from './AdminTable'
import { approveAdminExpense, getAdminExpense, getAdminExpenses, rejectAdminExpense, reimburseExpense, type AdminExpense } from '../services/admin'
export function AdminExpenses() {
  const [expenses, setExpenses] = useState<AdminExpense[]>([]); const [pagination, setPagination] = useState({ page: 1, total_pages: 1 }); const [state, setState] = useState(''); const [search, setSearch] = useState(''); const [details, setDetails] = useState<AdminExpense | null>(null); const [error, setError] = useState('')
  function load(page = 1) { getAdminExpenses({ page, per_page: 8, state, search }).then((result) => { setExpenses(result.expenses); setPagination(result.pagination) }).catch((reason: Error) => setError(reason.message)) }
  useEffect(() => { load() }, [state, search]) // eslint-disable-line react-hooks/exhaustive-deps
  async function reimburse(expense: AdminExpense) { const reference = window.prompt('Payment reference'); if (!reference) return; try { await reimburseExpense(expense.id, reference); load(pagination.page) } catch (reason) { setError(reason instanceof Error ? reason.message : 'Unable to reimburse expense.') } }
  async function review(expense: AdminExpense, action: 'approve' | 'reject') { const comment = window.prompt(action === 'reject' ? 'Reason for rejection (required)' : 'Comment (optional)', ''); if (action === 'reject' && !comment) return; try { if (action === 'approve') await approveAdminExpense(expense.id, comment ?? ''); else await rejectAdminExpense(expense.id, comment ?? ''); load(pagination.page) } catch (reason) { setError(reason instanceof Error ? reason.message : 'Unable to review expense.') } }
  return <div><div className="panel-title"><div><p className="eyebrow">Review queue</p><h2>Expenses</h2></div></div>{error && <p className="error-message">{error}</p>}<div className="toolbar"><input placeholder="Search title or owner" value={search} onChange={(event) => setSearch(event.target.value)}/><select value={state} onChange={(event) => setState(event.target.value)}><option value="">All states</option><option value="approved">Approved</option><option value="reimbursed">Reimbursed</option><option value="submitted">Submitted</option><option value="rejected">Rejected</option><option value="draft">Draft</option></select></div><AdminTable headers={['Expense', 'Owner', 'Amount', 'State', 'Actions']}>{expenses.map((expense) => <tr key={expense.id}><td>{expense.title}<small>{expense.category_name}</small></td><td>{expense.user_email}<small className="capitalize">{expense.user_role}</small></td><td>${expense.amount}</td><td><span className="state">{expense.state}</span></td><td><button className="table-button" onClick={() => getAdminExpense(expense.id).then(setDetails)}>Details</button>{expense.state === 'submitted' && (expense.user_role === 'employee' || expense.user_role === 'manager') && <><button className="table-button" onClick={() => review(expense, 'approve')}>Approve</button><button className="table-button danger-button" onClick={() => review(expense, 'reject')}>Reject</button></>}{expense.state === 'approved' && <button className="table-button" onClick={() => reimburse(expense)}>Reimburse</button>}</td></tr>)}</AdminTable><AdminPagination page={pagination.page} totalPages={pagination.total_pages} onChange={load}/>{details && <div className="detail-drawer"><div className="panel-title"><h3>{details.title}</h3><button className="text-button" onClick={() => setDetails(null)}>Close</button></div><p>{details.description || 'No description.'}</p><p className="muted">{details.user_email} · {details.spent_date} · ${details.amount}</p>{details.payment_reference && <p className="payment-reference"><strong>Payment reference:</strong> {details.payment_reference}</p>}<h4>History</h4>{details.history.map((item) => <div className="history-row" key={item.id}><strong>{stateName(item.prev_state)} To {stateName(item.next_state)}</strong><span>{item.changed_by ?? 'System'} · {new Date(item.created_at).toLocaleString()}</span></div>)}</div>}</div>
}

const states = ['draft', 'submitted', 'approved', 'rejected', 'reimbursed']
function stateName(state: number | null) {
  return state === null ? 'Unknown' : states[state] ?? 'Unknown'
}